In [1]:
import os

In [2]:
%pwd

'd:\\vehicle_insurance_fraud_detection\\research'

In [3]:
os.chdir("../")

In [4]:
%pwd

'd:\\vehicle_insurance_fraud_detection'

In [5]:
import pandas as pd

In [6]:
data= pd.read_csv("artifacts/data_ingestion/insurance fraud claims.csv")
data.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

In [8]:
data.isnull().sum()

months_as_customer                0
age                               0
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 0
policy_annual_premium             0
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           0
insured_occupation                0
insured_hobbies                   0
insured_relationship              0
capital-gains                     0
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            91
incident_state                    0
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                0
injury_claim                      0
property_claim                    0
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

In [9]:
data.shape

(1000, 40)

In [10]:
data.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported', '_c39'],
      dtype='object')

In [11]:
data.drop(['age', 'policy_number', 'policy_bind_date', 'insured_zip', 'insured_sex',
          'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship','collision_type','property_damage', 'capital-gains', 'capital-loss',
         'incident_date','incident_location', 'incident_hour_of_the_day','_c39'],axis=1,inplace=True)

In [12]:
filtered_data = data[(data['police_report_available'] == '?') & (data['authorities_contacted'] != 'Other')]
police_report_available_mode = data['police_report_available'].mode()[0]
data.loc[data['police_report_available'] == '?', 'police_report_available'] = 'yes'
data

,months_as_customer,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,incident_type,incident_severity,authorities_contacted,incident_state,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,OH,250/500,1000,1406.91,0,Single Vehicle Collision,Major Damage,Police,SC,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,IN,250/500,2000,1197.22,5000000,Vehicle Theft,Minor Damage,Police,VA,...,0,yes,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,OH,100/300,2000,1413.14,5000000,Multi-vehicle Collision,Minor Damage,Police,NY,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,IL,250/500,2000,1415.74,6000000,Single Vehicle Collision,Major Damage,Police,OH,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,IL,500/1000,1000,1583.91,6000000,Vehicle Theft,Minor Damage,NaN,NY,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,OH,500/1000,1000,1310.80,0,Single Vehicle Collision,Minor Damage,Fire,NC,...,1,yes,87200,17440,8720,61040,Honda,Accord,2006,N
996,285,IL,100/300,1000,1436.79,0,Single Vehicle Collision,Major Damage,Fire,SC,...,3,yes,108480,18080,18080,72320,Volkswagen,Passat,2015,N
997,130,OH,250/500,500,1383.49,3000000,Multi-vehicle Collision,Minor Damage,Police,NC,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
998,458,IL,500/1000,2000,1356.92,5000000,Single Vehicle Collision,Major Damage,Other,NY,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
999,456,OH,250/500,1000,766.19,0,Parked Car,Minor Damage,Police,WV,...,3,yes,5060,460,920,3680,Mercedes,E400,2007,N

In [13]:
data = data[data["umbrella_limit"] != -1000000]
data

,months_as_customer,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,incident_type,incident_severity,authorities_contacted,incident_state,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,OH,250/500,1000,1406.91,0,Single Vehicle Collision,Major Damage,Police,SC,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,IN,250/500,2000,1197.22,5000000,Vehicle Theft,Minor Damage,Police,VA,...,0,yes,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,OH,100/300,2000,1413.14,5000000,Multi-vehicle Collision,Minor Damage,Police,NY,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,IL,250/500,2000,1415.74,6000000,Single Vehicle Collision,Major Damage,Police,OH,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,IL,500/1000,1000,1583.91,6000000,Vehicle Theft,Minor Damage,NaN,NY,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,OH,500/1000,1000,1310.80,0,Single Vehicle Collision,Minor Damage,Fire,NC,...,1,yes,87200,17440,8720,61040,Honda,Accord,2006,N
996,285,IL,100/300,1000,1436.79,0,Single Vehicle Collision,Major Damage,Fire,SC,...,3,yes,108480,18080,18080,72320,Volkswagen,Passat,2015,N
997,130,OH,250/500,500,1383.49,3000000,Multi-vehicle Collision,Minor Damage,Police,NC,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
998,458,IL,500/1000,2000,1356.92,5000000,Single Vehicle Collision,Major Damage,Other,NY,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
999,456,OH,250/500,1000,766.19,0,Parked Car,Minor Damage,Police,WV,...,3,yes,5060,460,920,3680,Mercedes,E400,2007,N

In [14]:
data[data["authorities_contacted"].isnull()]["fraud_reported"].value_counts()

fraud_reported
N    85
Y     6
Name: count, dtype: int64

In [15]:
data = data.copy()  
data.dropna(subset=['authorities_contacted'], inplace=True)

In [16]:
data.isnull().sum()

months_as_customer             0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
incident_type                  0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
number_of_vehicles_involved    0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud_reported                 0
dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 908 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           908 non-null    int64
 1   policy_state                 908 non-null    object
 2   policy_csl                   908 non-null    object
 3   policy_deductable            908 non-null    int64
 4   policy_annual_premium        908 non-null    float64
 5   umbrella_limit               908 non-null    int64
 6   incident_type                908 non-null    object
 7   incident_severity            908 non-null    object
 8   authorities_contacted        908 non-null    object
 9   incident_state               908 non-null    object
 10  incident_city                908 non-null    object
 11  number_of_vehicles_involved  908 non-null    int64
 12  bodily_injuries              908 non-null    int64
 13  witnesses                    908 non-null    int64
 14  police_report_available      908 non-null    object
 15  total_claim_amount           908 non-null    int64
 16  injury_claim                 908 non-null    int64
 17  property_claim               908 non-null    int64
 18  vehicle_claim                908 non-null    int64
 19  auto_make                    908 non-null    object
 20  auto_model                   908 non-null    object
 21  auto_year                    908 non-null    int64
 22  fraud_reported               908 non-null    object
dtypes: float64(1), int64(11), object(11)
memory usage: 170.2+ KB

In [18]:
from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class DataValidationConfig:
    unzip_data_dir: Path
    STATUS_FILE: str
    root_dir: Path
    all_schema: dict

In [19]:
from src.vifd.constants import *
from src.vifd.utils.common import read_yaml, create_directories

In [20]:
class ConfigurationManager:
    def __init__(
            self,
            config_filepath=CONFIG_FILE_PATH,
            params_filepath=CONFIG_FILE_PATH,
            schema_filepath=SCHEMA_FILE_PATH
    ):
        self.config = read_yaml(config_filepath)
        self.params = read_yaml(params_filepath)
        self.schema = read_yaml(schema_filepath)

        create_directories([self.config.artifacts_root])

    def get_data_validation_config(self) -> DataValidationConfig:
        config = self.config.data_validation
        schema = self.schema.COLUMNS

        create_directories([config.root_dir])

        data_validation_config = DataValidationConfig(
            unzip_data_dir=config.unzip_data_dir,
            STATUS_FILE=config.STATUS_FILE,
            root_dir=config.root_dir,
            all_schema=schema,
        )

        return data_validation_config

In [21]:
import os
import pandas as pd
from src.vifd import logger

In [34]:
class DataValidation:
    def __init__(self, config:DataValidationConfig):
        self.config = config

    def validate_all_columns(self):
        try:
            data = pd.read_csv(self.config.unzip_data_dir)
            self.clean_data(data)
            validation_status = self.check_schema(data)
            with open(self.config.STATUS_FILE, 'w') as f:
                f.write(f"Validation status: {validation_status}")
            return validation_status
        except Exception as e:
            raise e
        

    def clean_data(self, data):
        data.drop(['age', 'policy_number', 'policy_bind_date', 'insured_zip', 'insured_sex',
                   'insured_education_level', 'insured_occupation', 'insured_hobbies',
                   'insured_relationship', 'collision_type', 'property_damage', 'capital-gains',
                   'capital-loss', 'incident_date', 'incident_location', 'incident_hour_of_the_day',
                   '_c39'], axis=1, inplace=True)
        filtered_data = data[(data['police_report_available'] == '?') & (data['authorities_contacted'] != 'Other')]
        police_report_available_mode = data['police_report_available'].mode()[0]
        data.loc[data['police_report_available'] == '?', 'police_report_available'] = 'yes'
        data = data[data["umbrella_limit"] != -1000000]
        data[data["authorities_contacted"].isnull()]["fraud_reported"].value_counts()
        data = data.copy()  
        data.dropna(subset=['authorities_contacted'], inplace=True)
        data.to_csv(os.path.join(self.config.root_dir, "cleaned_data.csv"))
    def check_schema(self, data):
        all_cols = list(data.columns)
        all_schema = self.config.all_schema.keys()
        for col in all_cols:
            if col not in all_schema:
                return False
        return True

In [35]:
try:
    config = ConfigurationManager()
    data_validation_config = config.get_data_validation_config()
    data_validation = DataValidation(config=data_validation_config)
    data_validation.validate_all_columns()
except Exception as e:
    raise e

[2024-01-01 00:04:47,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:04:47,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-01 00:04:47,142: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-01-01 00:04:47,144: INFO: common: created directory at: artifacts]
[2024-01-01 00:04:47,146: INFO: common: created directory at: artifacts/data_validation]